// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADATWyNk8i9gFObun9uyI4TvwHQJXoM0c',
    appId: '1:8384521890:web:da45756533d0fcda7b99fb',
    messagingSenderId: '8384521890',
    projectId: 'myroomie-55cff',
    authDomain: 'myroomie-55cff.firebaseapp.com',
    storageBucket: 'myroomie-55cff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuWRz5bb40I24V3Bt52BugkEmXGgNmQxs',
    appId: '1:8384521890:android:d38d49dbfea66a527b99fb',
    messagingSenderId: '8384521890',
    projectId: 'myroomie-55cff',
    storageBucket: 'myroomie-55cff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVECdQLpjM1Kd0M_5r_OABQ_kcS01INLo',
    appId: '1:8384521890:ios:9cbb2f934bb0265f7b99fb',
    messagingSenderId: '8384521890',
    projectId: 'myroomie-55cff',
    storageBucket: 'myroomie-55cff.appspot.com',
    iosClientId: '8384521890-jleahktrqero0ol3dm1dji5n7dk0o0ch.apps.googleusercontent.com',
    iosBundleId: 'com.suryaa62.myroomie',
  );
}
